# NOTE: NOT USED
# Unless we need to strip the /ig - we just re-use the existing ingress /ig patho
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT,GET,POST,HEAD,PATCH,DELETE"
    nginx.ingress.kubernetes.io/cors-allow-headers: "authorization,x-requested-with,cache-control,content-type,x-openidm-nosession,x-openidm-password,x-openidm-username,if-match,if-none-match"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    # Add your allowed origins here...
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:8888"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Expose-Headers: WWW-Authenticate";
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    #certmanager.k8s.io/cluster-issuer: "ca-issuer"
  name: forgerock-ig
spec:
  rules:
  - host: $(NAMESPACE).$(SUBDOMAIN).$(DOMAIN)
    http:
      - backend:
          serviceName: ig
          servicePort: 80
        path: /ig
  tls:
  - hosts:
    - $(NAMESPACE).$(SUBDOMAIN).$(DOMAIN)
    secretName: sslcert